# Filtragem, Seleção e Agregação de Dados
Este notebook demonstra técnicas fundamentais de manipulação de dados em Python usando pandas:

Filtragem de dados

Seleção de colunas e linhas

Agregação de dados

In [1]:
import pandas as pd
import numpy as np

# Criando um DataFrame de exemplo
dados = {
    'Nome': ['João', 'Maria', 'Pedro', 'Ana', 'Carlos', 'Julia', 'Lucas', 'Beatriz'],
    'Idade': [25, 30, 35, 28, 40, 22, 33, 27],
    'Cidade': ['São Paulo', 'Rio de Janeiro', 'Belo Horizonte', 'São Paulo', 
               'Rio de Janeiro', 'Belo Horizonte', 'São Paulo', 'Rio de Janeiro'],
    'Salário': [5000, 6000, 4500, 7000, 5500, 4000, 6500, 4800],
    'Departamento': ['TI', 'RH', 'Vendas', 'TI', 'Vendas', 'RH', 'TI', 'Vendas']
}

df = pd.DataFrame(dados)
df

      Nome  Idade          Cidade  Salário Departamento
0     João     25       São Paulo     5000           TI
1    Maria     30  Rio de Janeiro     6000           RH
2    Pedro     35  Belo Horizonte     4500       Vendas
3      Ana     28       São Paulo     7000           TI
4   Carlos     40  Rio de Janeiro     5500       Vendas
5    Julia     22  Belo Horizonte     4000           RH
6    Lucas     33       São Paulo     6500           TI
7  Beatriz     27  Rio de Janeiro     4800       Vendas

## 1. Filtragem de Dados
A filtragem permite selecionar linhas com base em condições específicas.

In [4]:
df['Salário'] > 50009

0    False
1    False
2    False
3    False
4    False
5    False
6    False
7    False
Name: Salário, dtype: bool

In [6]:
# Filtrando pessoas com salário maior que 5000
df[df['Salário'] > 5000]

     Nome  Idade          Cidade  Salário Departamento
1   Maria     30  Rio de Janeiro     6000           RH
3     Ana     28       São Paulo     7000           TI
4  Carlos     40  Rio de Janeiro     5500       Vendas
6   Lucas     33       São Paulo     6500           TI

In [5]:
# Filtrando pessoas do departamento de TI
df[df['Departamento'] == 'TI']

    Nome  Idade     Cidade  Salário Departamento
0   João     25  São Paulo     5000           TI
3    Ana     28  São Paulo     7000           TI
6  Lucas     33  São Paulo     6500           TI

In [7]:
# Filtrando com múltiplas condições (AND)
df[(df['Salário'] > 5000) & (df['Idade'] < 30)]

  Nome  Idade     Cidade  Salário Departamento
3  Ana     28  São Paulo     7000           TI

## 2. Seleção de Dados
A seleção permite escolher colunas específicas ou combinações de linhas e colunas.

In [8]:
df[['Nome', 'Salário']]

      Nome  Salário
0     João     5000
1    Maria     6000
2    Pedro     4500
3      Ana     7000
4   Carlos     5500
5    Julia     4000
6    Lucas     6500
7  Beatriz     4800

In [9]:
# Selecionando colunas específicas
df[['Nome', 'Salário', 'Departamento']]

      Nome  Salário Departamento
0     João     5000           TI
1    Maria     6000           RH
2    Pedro     4500       Vendas
3      Ana     7000           TI
4   Carlos     5500       Vendas
5    Julia     4000           RH
6    Lucas     6500           TI
7  Beatriz     4800       Vendas

In [10]:
# Selecionando linhas e colunas específicas
df.loc[df['Idade'] > 30, 'Salário']

2    4500
4    5500
6    6500
Name: Salário, dtype: int64

## 3. Agregação de Dados
A agregação permite resumir os dados usando funções estatísticas.

In [11]:
# Média de salário por departamento
df.groupby('Departamento')['Salário'].mean()

Departamento
RH        5000.000000
TI        6166.666667
Vendas    4933.333333
Name: Salário, dtype: float64

In [12]:
# Múltiplas agregações por departamento
df.groupby('Departamento').agg({
    'Salário': ['mean', 'min', 'max', 'count'],
    'Idade': 'mean'
})

                  Salário                        Idade
                     mean   min   max count       mean
Departamento
RH            5000.000000  4000  6000     2  26.000000
TI            6166.666667  5000  7000     3  28.666667
Vendas        4933.333333  4500  5500     3  34.000000

In [13]:
# Agregação por múltiplas colunas
df.groupby(['Departamento', 'Cidade'])['Salário'].mean()

Departamento  Cidade
RH            Belo Horizonte    4000.000000
              Rio de Janeiro    6000.000000
TI            São Paulo         6166.666667
Vendas        Belo Horizonte    4500.000000
              Rio de Janeiro    5150.000000
Name: Salário, dtype: float64

## 4. Exemplo Prático Combinado
Vamos combinar filtragem, seleção e agregação em um exemplo prático.

In [15]:
# Exemplo: Média salarial por departamento para pessoas com mais de 25 anos
df[df['Idade'] > 25].groupby('Departamento')['Salário'].mean()

Departamento
RH        6000.000000
TI        6750.000000
Vendas    4933.333333
Name: Salário, dtype: float64